// generated by _generateConnectorLists.ts. Do not modify by hand
import {default as connectorFinch} from '@openint/connector-finch/client'
import {default as connectorMerge} from '@openint/connector-merge/client'
import {default as connectorOnebrick} from '@openint/connector-onebrick/client'
import {default as connectorPlaid} from '@openint/connector-plaid/client'
import {default as connectorTeller} from '@openint/connector-teller/client'
import {default as connectorYodlee} from '@openint/connector-yodlee/client'

export const clientConnectors = {
  finch: connectorFinch,
  merge: connectorMerge,
  onebrick: connectorOnebrick,
  plaid: connectorPlaid,
  teller: connectorTeller,
  yodlee: connectorYodlee,
}
