// generated by _generateConnectorLists.ts. Do not modify by hand
import {default as connectorAirtable} from '@openint/connector-airtable/def'
import {default as connectorApollo} from '@openint/connector-apollo/def'
import {default as connectorBeancount} from '@openint/connector-beancount/def'
import {default as connectorBrex} from '@openint/connector-brex/def'
import {default as connectorCoda} from '@openint/connector-coda/def'
import {default as connectorDebug} from '@openint/connector-debug/def'
import {default as connectorDiscord} from '@openint/connector-discord/def'
import {default as connectorFinch} from '@openint/connector-finch/def'
import {default as connectorFirebase} from '@openint/connector-firebase/def'
import {default as connectorForeceipt} from '@openint/connector-foreceipt/def'
import {default as connectorFs} from '@openint/connector-fs/def'
import {default as connectorGoogle} from '@openint/connector-google/def'
import {default as connectorGreenhouse} from '@openint/connector-greenhouse/def'
import {default as connectorHeron} from '@openint/connector-heron/def'
import {default as connectorHubspot} from '@openint/connector-hubspot/def'
import {default as connectorLever} from '@openint/connector-lever/def'
import {default as connectorLunchmoney} from '@openint/connector-lunchmoney/def'
import {default as connectorMercury} from '@openint/connector-mercury/def'
import {default as connectorMerge} from '@openint/connector-merge/def'
import {default as connectorMongodb} from '@openint/connector-mongodb/def'
import {default as connectorMoota} from '@openint/connector-moota/def'
import {default as connectorOnebrick} from '@openint/connector-onebrick/def'
import {default as connectorOutreach} from '@openint/connector-outreach/def'
import {default as connectorPipedrive} from '@openint/connector-pipedrive/def'
import {default as connectorPlaid} from '@openint/connector-plaid/def'
import {default as connectorPostgres} from '@openint/connector-postgres/def'
import {default as connectorQbo} from '@openint/connector-qbo/def'
import {default as connectorRamp} from '@openint/connector-ramp/def'
import {default as connectorRevert} from '@openint/connector-revert/def'
import {default as connectorSalesforce} from '@openint/connector-salesforce/def'
import {default as connectorSalesloft} from '@openint/connector-salesloft/def'
import {default as connectorSaltedge} from '@openint/connector-saltedge/def'
import {default as connectorSplitwise} from '@openint/connector-splitwise/def'
import {default as connectorSpreadsheet} from '@openint/connector-spreadsheet/def'
import {default as connectorStripe} from '@openint/connector-stripe/def'
import {default as connectorTeller} from '@openint/connector-teller/def'
import {default as connectorToggl} from '@openint/connector-toggl/def'
import {default as connectorTwenty} from '@openint/connector-twenty/def'
import {default as connectorVenmo} from '@openint/connector-venmo/def'
import {default as connectorWebhook} from '@openint/connector-webhook/def'
import {default as connectorWise} from '@openint/connector-wise/def'
import {default as connectorXero} from '@openint/connector-xero/def'
import {default as connectorYodlee} from '@openint/connector-yodlee/def'

export const defConnectors = {
  airtable: connectorAirtable,
  apollo: connectorApollo,
  beancount: connectorBeancount,
  brex: connectorBrex,
  coda: connectorCoda,
  debug: connectorDebug,
  discord: connectorDiscord,
  finch: connectorFinch,
  firebase: connectorFirebase,
  foreceipt: connectorForeceipt,
  fs: connectorFs,
  google: connectorGoogle,
  greenhouse: connectorGreenhouse,
  heron: connectorHeron,
  hubspot: connectorHubspot,
  lever: connectorLever,
  lunchmoney: connectorLunchmoney,
  mercury: connectorMercury,
  merge: connectorMerge,
  mongodb: connectorMongodb,
  moota: connectorMoota,
  onebrick: connectorOnebrick,
  outreach: connectorOutreach,
  pipedrive: connectorPipedrive,
  plaid: connectorPlaid,
  postgres: connectorPostgres,
  qbo: connectorQbo,
  ramp: connectorRamp,
  revert: connectorRevert,
  salesforce: connectorSalesforce,
  salesloft: connectorSalesloft,
  saltedge: connectorSaltedge,
  splitwise: connectorSplitwise,
  spreadsheet: connectorSpreadsheet,
  stripe: connectorStripe,
  teller: connectorTeller,
  toggl: connectorToggl,
  twenty: connectorTwenty,
  venmo: connectorVenmo,
  webhook: connectorWebhook,
  wise: connectorWise,
  xero: connectorXero,
  yodlee: connectorYodlee,
}
