// generated by _generateConnectorLists.ts. Do not modify by hand
import {default as connectorAirtable} from '@openint/connector-airtable/server'
import {default as connectorApollo} from '@openint/connector-apollo/server'
import {default as connectorBeancount} from '@openint/connector-beancount/server'
import {default as connectorBrex} from '@openint/connector-brex/server'
import {default as connectorCoda} from '@openint/connector-coda/server'
import {default as connectorDebug} from '@openint/connector-debug/server'
import {default as connectorDiscord} from '@openint/connector-discord/server'
import {default as connectorFinch} from '@openint/connector-finch/server'
import {default as connectorFirebase} from '@openint/connector-firebase/server'
import {default as connectorForeceipt} from '@openint/connector-foreceipt/server'
import {default as connectorFs} from '@openint/connector-fs/server'
import {default as connectorGoogle} from '@openint/connector-google/server'
import {default as connectorGreenhouse} from '@openint/connector-greenhouse/server'
import {default as connectorHeron} from '@openint/connector-heron/server'
import {default as connectorHubspot} from '@openint/connector-hubspot/server'
import {default as connectorLever} from '@openint/connector-lever/server'
import {default as connectorLunchmoney} from '@openint/connector-lunchmoney/server'
import {default as connectorMerge} from '@openint/connector-merge/server'
import {default as connectorMongodb} from '@openint/connector-mongodb/server'
import {default as connectorMoota} from '@openint/connector-moota/server'
import {default as connectorOnebrick} from '@openint/connector-onebrick/server'
import {default as connectorOutreach} from '@openint/connector-outreach/server'
import {default as connectorPipedrive} from '@openint/connector-pipedrive/server'
import {default as connectorPlaid} from '@openint/connector-plaid/server'
import {default as connectorPostgres} from '@openint/connector-postgres/server'
import {default as connectorQbo} from '@openint/connector-qbo/server'
import {default as connectorRamp} from '@openint/connector-ramp/server'
import {default as connectorRevert} from '@openint/connector-revert/server'
import {default as connectorSalesforce} from '@openint/connector-salesforce/server'
import {default as connectorSalesloft} from '@openint/connector-salesloft/server'
import {default as connectorSaltedge} from '@openint/connector-saltedge/server'
import {default as connectorSplitwise} from '@openint/connector-splitwise/server'
import {default as connectorSpreadsheet} from '@openint/connector-spreadsheet/server'
import {default as connectorStripe} from '@openint/connector-stripe/server'
import {default as connectorTeller} from '@openint/connector-teller/server'
import {default as connectorToggl} from '@openint/connector-toggl/server'
import {default as connectorTwenty} from '@openint/connector-twenty/server'
import {default as connectorWebhook} from '@openint/connector-webhook/server'
import {default as connectorWise} from '@openint/connector-wise/server'
import {default as connectorXero} from '@openint/connector-xero/server'
import {default as connectorYodlee} from '@openint/connector-yodlee/server'

export const serverConnectors = {
  airtable: connectorAirtable,
  apollo: connectorApollo,
  beancount: connectorBeancount,
  brex: connectorBrex,
  coda: connectorCoda,
  debug: connectorDebug,
  discord: connectorDiscord,
  finch: connectorFinch,
  firebase: connectorFirebase,
  foreceipt: connectorForeceipt,
  fs: connectorFs,
  google: connectorGoogle,
  greenhouse: connectorGreenhouse,
  heron: connectorHeron,
  hubspot: connectorHubspot,
  lever: connectorLever,
  lunchmoney: connectorLunchmoney,
  merge: connectorMerge,
  mongodb: connectorMongodb,
  moota: connectorMoota,
  onebrick: connectorOnebrick,
  outreach: connectorOutreach,
  pipedrive: connectorPipedrive,
  plaid: connectorPlaid,
  postgres: connectorPostgres,
  qbo: connectorQbo,
  ramp: connectorRamp,
  revert: connectorRevert,
  salesforce: connectorSalesforce,
  salesloft: connectorSalesloft,
  saltedge: connectorSaltedge,
  splitwise: connectorSplitwise,
  spreadsheet: connectorSpreadsheet,
  stripe: connectorStripe,
  teller: connectorTeller,
  toggl: connectorToggl,
  twenty: connectorTwenty,
  webhook: connectorWebhook,
  wise: connectorWise,
  xero: connectorXero,
  yodlee: connectorYodlee,
}
