// generated by _generateConnectorLists.ts. Do not modify by hand
import {default as connectorAirtable_def} from '@openint/connector-airtable/def'
import {default as connectorAirtable_server} from '@openint/connector-airtable/server'
import {default as connectorApollo_def} from '@openint/connector-apollo/def'
import {default as connectorApollo_server} from '@openint/connector-apollo/server'
import {default as connectorBeancount_def} from '@openint/connector-beancount/def'
import {default as connectorBeancount_server} from '@openint/connector-beancount/server'
import {default as connectorBrex_def} from '@openint/connector-brex/def'
import {default as connectorBrex_server} from '@openint/connector-brex/server'
import {default as connectorCoda_def} from '@openint/connector-coda/def'
import {default as connectorCoda_server} from '@openint/connector-coda/server'
import {default as connectorDebug_def} from '@openint/connector-debug/def'
import {default as connectorDebug_server} from '@openint/connector-debug/server'
import {default as connectorDiscord_def} from '@openint/connector-discord/def'
import {default as connectorDiscord_server} from '@openint/connector-discord/server'
import {default as connectorFinch_def} from '@openint/connector-finch/def'
import {default as connectorFinch_server} from '@openint/connector-finch/server'
import {default as connectorFirebase_def} from '@openint/connector-firebase/def'
import {default as connectorFirebase_server} from '@openint/connector-firebase/server'
import {default as connectorForeceipt_def} from '@openint/connector-foreceipt/def'
import {default as connectorForeceipt_server} from '@openint/connector-foreceipt/server'
import {default as connectorFs_def} from '@openint/connector-fs/def'
import {default as connectorFs_server} from '@openint/connector-fs/server'
import {default as connectorGoogle_def} from '@openint/connector-google/def'
import {default as connectorGoogle_server} from '@openint/connector-google/server'
import {default as connectorGreenhouse_def} from '@openint/connector-greenhouse/def'
import {default as connectorGreenhouse_server} from '@openint/connector-greenhouse/server'
import {default as connectorHeron_def} from '@openint/connector-heron/def'
import {default as connectorHeron_server} from '@openint/connector-heron/server'
import {default as connectorHubspot_def} from '@openint/connector-hubspot/def'
import {default as connectorHubspot_server} from '@openint/connector-hubspot/server'
import {default as connectorLever_def} from '@openint/connector-lever/def'
import {default as connectorLever_server} from '@openint/connector-lever/server'
import {default as connectorLunchmoney_def} from '@openint/connector-lunchmoney/def'
import {default as connectorLunchmoney_server} from '@openint/connector-lunchmoney/server'
import {default as connectorMercury_def} from '@openint/connector-mercury/def'
import {default as connectorMerge_def} from '@openint/connector-merge/def'
import {default as connectorMerge_server} from '@openint/connector-merge/server'
import {default as connectorMongodb_def} from '@openint/connector-mongodb/def'
import {default as connectorMongodb_server} from '@openint/connector-mongodb/server'
import {default as connectorMoota_def} from '@openint/connector-moota/def'
import {default as connectorMoota_server} from '@openint/connector-moota/server'
import {default as connectorOnebrick_def} from '@openint/connector-onebrick/def'
import {default as connectorOnebrick_server} from '@openint/connector-onebrick/server'
import {default as connectorOutreach_def} from '@openint/connector-outreach/def'
import {default as connectorOutreach_server} from '@openint/connector-outreach/server'
import {default as connectorPipedrive_def} from '@openint/connector-pipedrive/def'
import {default as connectorPipedrive_server} from '@openint/connector-pipedrive/server'
import {default as connectorPlaid_def} from '@openint/connector-plaid/def'
import {default as connectorPlaid_server} from '@openint/connector-plaid/server'
import {default as connectorPostgres_def} from '@openint/connector-postgres/def'
import {default as connectorPostgres_server} from '@openint/connector-postgres/server'
import {default as connectorQbo_def} from '@openint/connector-qbo/def'
import {default as connectorQbo_server} from '@openint/connector-qbo/server'
import {default as connectorRamp_def} from '@openint/connector-ramp/def'
import {default as connectorRamp_server} from '@openint/connector-ramp/server'
import {default as connectorRevert_def} from '@openint/connector-revert/def'
import {default as connectorRevert_server} from '@openint/connector-revert/server'
import {default as connectorSalesforce_def} from '@openint/connector-salesforce/def'
import {default as connectorSalesforce_server} from '@openint/connector-salesforce/server'
import {default as connectorSalesloft_def} from '@openint/connector-salesloft/def'
import {default as connectorSalesloft_server} from '@openint/connector-salesloft/server'
import {default as connectorSaltedge_def} from '@openint/connector-saltedge/def'
import {default as connectorSaltedge_server} from '@openint/connector-saltedge/server'
import {default as connectorSplitwise_def} from '@openint/connector-splitwise/def'
import {default as connectorSplitwise_server} from '@openint/connector-splitwise/server'
import {default as connectorSpreadsheet_def} from '@openint/connector-spreadsheet/def'
import {default as connectorSpreadsheet_server} from '@openint/connector-spreadsheet/server'
import {default as connectorStripe_def} from '@openint/connector-stripe/def'
import {default as connectorStripe_server} from '@openint/connector-stripe/server'
import {default as connectorTeller_def} from '@openint/connector-teller/def'
import {default as connectorTeller_server} from '@openint/connector-teller/server'
import {default as connectorToggl_def} from '@openint/connector-toggl/def'
import {default as connectorToggl_server} from '@openint/connector-toggl/server'
import {default as connectorTwenty_def} from '@openint/connector-twenty/def'
import {default as connectorTwenty_server} from '@openint/connector-twenty/server'
import {default as connectorVenmo_def} from '@openint/connector-venmo/def'
import {default as connectorWebhook_def} from '@openint/connector-webhook/def'
import {default as connectorWebhook_server} from '@openint/connector-webhook/server'
import {default as connectorWise_def} from '@openint/connector-wise/def'
import {default as connectorWise_server} from '@openint/connector-wise/server'
import {default as connectorXero_def} from '@openint/connector-xero/def'
import {default as connectorXero_server} from '@openint/connector-xero/server'
import {default as connectorYodlee_def} from '@openint/connector-yodlee/def'
import {default as connectorYodlee_server} from '@openint/connector-yodlee/server'

const connectorAirtable = {
  ...connectorAirtable_def,
  ...connectorAirtable_server,
}

const connectorApollo = {
  ...connectorApollo_def,
  ...connectorApollo_server,
}

const connectorBeancount = {
  ...connectorBeancount_def,
  ...connectorBeancount_server,
}

const connectorBrex = {
  ...connectorBrex_def,
  ...connectorBrex_server,
}

const connectorCoda = {
  ...connectorCoda_def,
  ...connectorCoda_server,
}

const connectorDebug = {
  ...connectorDebug_def,
  ...connectorDebug_server,
}

const connectorDiscord = {
  ...connectorDiscord_def,
  ...connectorDiscord_server,
}

const connectorFinch = {
  ...connectorFinch_def,
  ...connectorFinch_server,
}

const connectorFirebase = {
  ...connectorFirebase_def,
  ...connectorFirebase_server,
}

const connectorForeceipt = {
  ...connectorForeceipt_def,
  ...connectorForeceipt_server,
}

const connectorFs = {
  ...connectorFs_def,
  ...connectorFs_server,
}

const connectorGoogle = {
  ...connectorGoogle_def,
  ...connectorGoogle_server,
}

const connectorGreenhouse = {
  ...connectorGreenhouse_def,
  ...connectorGreenhouse_server,
}

const connectorHeron = {
  ...connectorHeron_def,
  ...connectorHeron_server,
}

const connectorHubspot = {
  ...connectorHubspot_def,
  ...connectorHubspot_server,
}

const connectorLever = {
  ...connectorLever_def,
  ...connectorLever_server,
}

const connectorLunchmoney = {
  ...connectorLunchmoney_def,
  ...connectorLunchmoney_server,
}

const connectorMercury = {
  ...connectorMercury_def,
}

const connectorMerge = {
  ...connectorMerge_def,
  ...connectorMerge_server,
}

const connectorMongodb = {
  ...connectorMongodb_def,
  ...connectorMongodb_server,
}

const connectorMoota = {
  ...connectorMoota_def,
  ...connectorMoota_server,
}

const connectorOnebrick = {
  ...connectorOnebrick_def,
  ...connectorOnebrick_server,
}

const connectorOutreach = {
  ...connectorOutreach_def,
  ...connectorOutreach_server,
}

const connectorPipedrive = {
  ...connectorPipedrive_def,
  ...connectorPipedrive_server,
}

const connectorPlaid = {
  ...connectorPlaid_def,
  ...connectorPlaid_server,
}

const connectorPostgres = {
  ...connectorPostgres_def,
  ...connectorPostgres_server,
}

const connectorQbo = {
  ...connectorQbo_def,
  ...connectorQbo_server,
}

const connectorRamp = {
  ...connectorRamp_def,
  ...connectorRamp_server,
}

const connectorRevert = {
  ...connectorRevert_def,
  ...connectorRevert_server,
}

const connectorSalesforce = {
  ...connectorSalesforce_def,
  ...connectorSalesforce_server,
}

const connectorSalesloft = {
  ...connectorSalesloft_def,
  ...connectorSalesloft_server,
}

const connectorSaltedge = {
  ...connectorSaltedge_def,
  ...connectorSaltedge_server,
}

const connectorSplitwise = {
  ...connectorSplitwise_def,
  ...connectorSplitwise_server,
}

const connectorSpreadsheet = {
  ...connectorSpreadsheet_def,
  ...connectorSpreadsheet_server,
}

const connectorStripe = {
  ...connectorStripe_def,
  ...connectorStripe_server,
}

const connectorTeller = {
  ...connectorTeller_def,
  ...connectorTeller_server,
}

const connectorToggl = {
  ...connectorToggl_def,
  ...connectorToggl_server,
}

const connectorTwenty = {
  ...connectorTwenty_def,
  ...connectorTwenty_server,
}

const connectorVenmo = {
  ...connectorVenmo_def,
}

const connectorWebhook = {
  ...connectorWebhook_def,
  ...connectorWebhook_server,
}

const connectorWise = {
  ...connectorWise_def,
  ...connectorWise_server,
}

const connectorXero = {
  ...connectorXero_def,
  ...connectorXero_server,
}

const connectorYodlee = {
  ...connectorYodlee_def,
  ...connectorYodlee_server,
}

export const mergedConnectors = {
  airtable: connectorAirtable,
  apollo: connectorApollo,
  beancount: connectorBeancount,
  brex: connectorBrex,
  coda: connectorCoda,
  debug: connectorDebug,
  discord: connectorDiscord,
  finch: connectorFinch,
  firebase: connectorFirebase,
  foreceipt: connectorForeceipt,
  fs: connectorFs,
  google: connectorGoogle,
  greenhouse: connectorGreenhouse,
  heron: connectorHeron,
  hubspot: connectorHubspot,
  lever: connectorLever,
  lunchmoney: connectorLunchmoney,
  mercury: connectorMercury,
  merge: connectorMerge,
  mongodb: connectorMongodb,
  moota: connectorMoota,
  onebrick: connectorOnebrick,
  outreach: connectorOutreach,
  pipedrive: connectorPipedrive,
  plaid: connectorPlaid,
  postgres: connectorPostgres,
  qbo: connectorQbo,
  ramp: connectorRamp,
  revert: connectorRevert,
  salesforce: connectorSalesforce,
  salesloft: connectorSalesloft,
  saltedge: connectorSaltedge,
  splitwise: connectorSplitwise,
  spreadsheet: connectorSpreadsheet,
  stripe: connectorStripe,
  teller: connectorTeller,
  toggl: connectorToggl,
  twenty: connectorTwenty,
  venmo: connectorVenmo,
  webhook: connectorWebhook,
  wise: connectorWise,
  xero: connectorXero,
  yodlee: connectorYodlee,
}
