// generated by _generateConnectorLists.ts. Do not modify by hand

module.exports = [
  {
    name: 'airtable',
    dirName: 'connector-airtable',
    varName: 'connectorAirtable',
    imports: {
      def: '@openint/connector-airtable/def',
      server: '@openint/connector-airtable/server',
    },
  },
  {
    dirName: 'connector-alphavantage',
    varName: 'connectorAlphavantage',
    imports: {},
  },
  {
    name: 'apollo',
    dirName: 'connector-apollo',
    varName: 'connectorApollo',
    imports: {
      def: '@openint/connector-apollo/def',
      server: '@openint/connector-apollo/server',
    },
  },
  {
    name: 'beancount',
    dirName: 'connector-beancount',
    varName: 'connectorBeancount',
    imports: {
      def: '@openint/connector-beancount/def',
      server: '@openint/connector-beancount/server',
    },
  },
  {
    name: 'brex',
    dirName: 'connector-brex',
    varName: 'connectorBrex',
    imports: {
      def: '@openint/connector-brex/def',
      server: '@openint/connector-brex/server',
    },
  },
  {
    name: 'coda',
    dirName: 'connector-coda',
    varName: 'connectorCoda',
    imports: {
      def: '@openint/connector-coda/def',
      server: '@openint/connector-coda/server',
    },
  },
  {dirName: 'connector-copilot', varName: 'connectorCopilot', imports: {}},
  {
    name: 'debug',
    dirName: 'connector-debug',
    varName: 'connectorDebug',
    imports: {
      def: '@openint/connector-debug/def',
      server: '@openint/connector-debug/server',
    },
  },
  {
    name: 'discord',
    dirName: 'connector-discord',
    varName: 'connectorDiscord',
    imports: {
      def: '@openint/connector-discord/def',
      server: '@openint/connector-discord/server',
    },
  },
  {dirName: 'connector-expensify', varName: 'connectorExpensify', imports: {}},
  {
    name: 'finch',
    dirName: 'connector-finch',
    varName: 'connectorFinch',
    imports: {
      def: '@openint/connector-finch/def',
      client: '@openint/connector-finch/client',
      server: '@openint/connector-finch/server',
    },
  },
  {
    name: 'firebase',
    dirName: 'connector-firebase',
    varName: 'connectorFirebase',
    imports: {
      def: '@openint/connector-firebase/def',
      server: '@openint/connector-firebase/server',
    },
  },
  {
    name: 'foreceipt',
    dirName: 'connector-foreceipt',
    varName: 'connectorForeceipt',
    imports: {
      def: '@openint/connector-foreceipt/def',
      server: '@openint/connector-foreceipt/server',
    },
  },
  {
    name: 'fs',
    dirName: 'connector-fs',
    varName: 'connectorFs',
    imports: {
      def: '@openint/connector-fs/def',
      server: '@openint/connector-fs/server',
    },
  },
  {
    name: 'google',
    dirName: 'connector-google',
    varName: 'connectorGoogle',
    imports: {
      def: '@openint/connector-google/def',
      server: '@openint/connector-google/server',
    },
  },
  {
    name: 'greenhouse',
    dirName: 'connector-greenhouse',
    varName: 'connectorGreenhouse',
    imports: {
      def: '@openint/connector-greenhouse/def',
      server: '@openint/connector-greenhouse/server',
    },
  },
  {
    name: 'heron',
    dirName: 'connector-heron',
    varName: 'connectorHeron',
    imports: {
      def: '@openint/connector-heron/def',
      server: '@openint/connector-heron/server',
    },
  },
  {
    name: 'hubspot',
    dirName: 'connector-hubspot',
    varName: 'connectorHubspot',
    imports: {
      def: '@openint/connector-hubspot/def',
      server: '@openint/connector-hubspot/server',
    },
  },
  {
    name: 'lever',
    dirName: 'connector-lever',
    varName: 'connectorLever',
    imports: {
      def: '@openint/connector-lever/def',
      server: '@openint/connector-lever/server',
    },
  },
  {
    name: 'lunchmoney',
    dirName: 'connector-lunchmoney',
    varName: 'connectorLunchmoney',
    imports: {
      def: '@openint/connector-lunchmoney/def',
      server: '@openint/connector-lunchmoney/server',
    },
  },
  {
    name: 'mercury',
    dirName: 'connector-mercury',
    varName: 'connectorMercury',
    imports: {def: '@openint/connector-mercury/def'},
  },
  {
    name: 'merge',
    dirName: 'connector-merge',
    varName: 'connectorMerge',
    imports: {
      def: '@openint/connector-merge/def',
      client: '@openint/connector-merge/client',
      server: '@openint/connector-merge/server',
    },
  },
  {
    name: 'mongodb',
    dirName: 'connector-mongodb',
    varName: 'connectorMongodb',
    imports: {
      def: '@openint/connector-mongodb/def',
      server: '@openint/connector-mongodb/server',
    },
  },
  {
    name: 'moota',
    dirName: 'connector-moota',
    varName: 'connectorMoota',
    imports: {
      def: '@openint/connector-moota/def',
      server: '@openint/connector-moota/server',
    },
  },
  {
    name: 'onebrick',
    dirName: 'connector-onebrick',
    varName: 'connectorOnebrick',
    imports: {
      def: '@openint/connector-onebrick/def',
      client: '@openint/connector-onebrick/client',
      server: '@openint/connector-onebrick/server',
    },
  },
  {
    name: 'outreach',
    dirName: 'connector-outreach',
    varName: 'connectorOutreach',
    imports: {
      def: '@openint/connector-outreach/def',
      server: '@openint/connector-outreach/server',
    },
  },
  {
    name: 'pipedrive',
    dirName: 'connector-pipedrive',
    varName: 'connectorPipedrive',
    imports: {
      def: '@openint/connector-pipedrive/def',
      server: '@openint/connector-pipedrive/server',
    },
  },
  {
    name: 'plaid',
    dirName: 'connector-plaid',
    varName: 'connectorPlaid',
    imports: {
      def: '@openint/connector-plaid/def',
      client: '@openint/connector-plaid/client',
      server: '@openint/connector-plaid/server',
    },
  },
  {
    name: 'postgres',
    dirName: 'connector-postgres',
    varName: 'connectorPostgres',
    imports: {
      def: '@openint/connector-postgres/def',
      server: '@openint/connector-postgres/server',
    },
  },
  {
    name: 'qbo',
    dirName: 'connector-qbo',
    varName: 'connectorQbo',
    imports: {
      def: '@openint/connector-qbo/def',
      server: '@openint/connector-qbo/server',
    },
  },
  {
    name: 'ramp',
    dirName: 'connector-ramp',
    varName: 'connectorRamp',
    imports: {
      def: '@openint/connector-ramp/def',
      server: '@openint/connector-ramp/server',
    },
  },
  {
    name: 'revert',
    dirName: 'connector-revert',
    varName: 'connectorRevert',
    imports: {
      def: '@openint/connector-revert/def',
      server: '@openint/connector-revert/server',
    },
  },
  {
    name: 'salesforce',
    dirName: 'connector-salesforce',
    varName: 'connectorSalesforce',
    imports: {
      def: '@openint/connector-salesforce/def',
      server: '@openint/connector-salesforce/server',
    },
  },
  {
    name: 'salesloft',
    dirName: 'connector-salesloft',
    varName: 'connectorSalesloft',
    imports: {
      def: '@openint/connector-salesloft/def',
      server: '@openint/connector-salesloft/server',
    },
  },
  {
    name: 'saltedge',
    dirName: 'connector-saltedge',
    varName: 'connectorSaltedge',
    imports: {
      def: '@openint/connector-saltedge/def',
      server: '@openint/connector-saltedge/server',
    },
  },
  {
    name: 'splitwise',
    dirName: 'connector-splitwise',
    varName: 'connectorSplitwise',
    imports: {
      def: '@openint/connector-splitwise/def',
      server: '@openint/connector-splitwise/server',
    },
  },
  {
    name: 'spreadsheet',
    dirName: 'connector-spreadsheet',
    varName: 'connectorSpreadsheet',
    imports: {
      def: '@openint/connector-spreadsheet/def',
      server: '@openint/connector-spreadsheet/server',
    },
  },
  {
    name: 'stripe',
    dirName: 'connector-stripe',
    varName: 'connectorStripe',
    imports: {
      def: '@openint/connector-stripe/def',
      server: '@openint/connector-stripe/server',
    },
  },
  {
    name: 'teller',
    dirName: 'connector-teller',
    varName: 'connectorTeller',
    imports: {
      def: '@openint/connector-teller/def',
      client: '@openint/connector-teller/client',
      server: '@openint/connector-teller/server',
    },
  },
  {
    name: 'toggl',
    dirName: 'connector-toggl',
    varName: 'connectorToggl',
    imports: {
      def: '@openint/connector-toggl/def',
      server: '@openint/connector-toggl/server',
    },
  },
  {
    name: 'twenty',
    dirName: 'connector-twenty',
    varName: 'connectorTwenty',
    imports: {
      def: '@openint/connector-twenty/def',
      server: '@openint/connector-twenty/server',
    },
  },
  {
    name: 'venmo',
    dirName: 'connector-venmo',
    varName: 'connectorVenmo',
    imports: {def: '@openint/connector-venmo/def'},
  },
  {
    name: 'webhook',
    dirName: 'connector-webhook',
    varName: 'connectorWebhook',
    imports: {
      def: '@openint/connector-webhook/def',
      server: '@openint/connector-webhook/server',
    },
  },
  {
    name: 'wise',
    dirName: 'connector-wise',
    varName: 'connectorWise',
    imports: {
      def: '@openint/connector-wise/def',
      server: '@openint/connector-wise/server',
    },
  },
  {
    name: 'xero',
    dirName: 'connector-xero',
    varName: 'connectorXero',
    imports: {
      def: '@openint/connector-xero/def',
      server: '@openint/connector-xero/server',
    },
  },
  {
    name: 'yodlee',
    dirName: 'connector-yodlee',
    varName: 'connectorYodlee',
    imports: {
      def: '@openint/connector-yodlee/def',
      client: '@openint/connector-yodlee/client',
      server: '@openint/connector-yodlee/server',
    },
  },
]
